### ISSUE TITLE
[11.0] requeriments pypdf2 is more lower than oca/ocb

### ISSUE THREAD

**Issue by igallart** [OCA/report-print-send#186]
Hi, I think that the last update in requeriments is incorrect, version pypdf2 is 1.18, and ocb is 1.26. When I print reports it fails, and before it works. In runbot with that commit also fail. I think that is more correct with version 1.26 or more, like in requirements of ocb. And, if is in ocb, is necessary here?

**Comment by igallart** [comment]
Can anyone verify if the reports qweb work with pypdf2 1.18?

**Comment by igallart** [comment]
AttributeError: 'PdfFileWriter' object has no attribute 'appendPagesFromReader'

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/report-print-send/pull/188
Thanks!
